"""Lightweight course knowledge graph schema and utilities.

This module intentionally keeps the graph format simple and JSON-native so the
course graph can be generated by different extraction backends, including
LangChain's ``LLMGraphTransformer`` or a prompt-only fallback.
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterable
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Literal

NodeType = Literal[
    "Concept",
    "Algorithm",
    "Method",
    "Formula",
    "Metric",
    "Example",
    "Chapter",
    "Section",
    "Misconception",
]

RelationType = Literal[
    "part_of",
    "prerequisite_of",
    "related_to",
    "confusable_with",
    "used_for",
    "mitigates",
    "evaluated_by",
    "example_of",
    "evidence_in",
]

PedagogicalType = Literal[
    "definition",
    "example",
    "formula",
    "procedure",
    "contrast",
    "summary",
    "exercise",
    "misconception_correction",
    "other",
]

ALLOWED_NODE_TYPES: tuple[str, ...] = (
    "Concept",
    "Algorithm",
    "Method",
    "Formula",
    "Metric",
    "Example",
    "Chapter",
    "Section",
    "Misconception",
)

ALLOWED_RELATION_TYPES: tuple[str, ...] = (
    "part_of",
    "prerequisite_of",
    "related_to",
    "confusable_with",
    "used_for",
    "mitigates",
    "evaluated_by",
    "example_of",
    "evidence_in",
)

ALLOWED_PEDAGOGICAL_TYPES: tuple[str, ...] = (
    "definition",
    "example",
    "formula",
    "procedure",
    "contrast",
    "summary",
    "exercise",
    "misconception_correction",
    "other",
)


@dataclass
class CourseGraphNode:
    id: str
    name: str
    type: str = "Concept"
    aliases: list[str] = field(default_factory=list)
    chapter: str = ""
    section: str = ""
    definition: str = ""
    evidence_chunk_ids: list[str] = field(default_factory=list)
    confidence: float = 0.0


@dataclass
class CourseGraphEdge:
    source: str
    target: str
    type: str
    evidence_chunk_ids: list[str] = field(default_factory=list)
    confidence: float = 0.0
    rationale: str = ""


@dataclass
class ChunkConceptTag:
    chunk_id: str
    concept_ids: list[str] = field(default_factory=list)
    pedagogical_type: str = "other"
    confidence: float = 0.0


@dataclass
class MisconceptionItem:
    id: str
    concept_id: str
    wrong_belief: str
    correction: str
    confusable_concept_ids: list[str] = field(default_factory=list)
    evidence_chunk_ids: list[str] = field(default_factory=list)
    confidence: float = 0.0


@dataclass
class CourseGraph:
    course_name: str = ""
    version: str = "0.1"
    nodes: list[CourseGraphNode] = field(default_factory=list)
    edges: list[CourseGraphEdge] = field(default_factory=list)
    chunk_tags: list[ChunkConceptTag] = field(default_factory=list)
    misconceptions: list[MisconceptionItem] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def save(self, path: str | Path) -> None:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(self.to_dict(), ensure_ascii=False, indent=2), encoding="utf-8")

    @classmethod
    def load(cls, path: str | Path) -> CourseGraph:
        payload = json.loads(Path(path).read_text(encoding="utf-8"))
        return cls(
            course_name=payload.get("course_name", ""),
            version=payload.get("version", "0.1"),
            nodes=[CourseGraphNode(**item) for item in payload.get("nodes", [])],
            edges=[CourseGraphEdge(**item) for item in payload.get("edges", [])],
            chunk_tags=[ChunkConceptTag(**item) for item in payload.get("chunk_tags", [])],
            misconceptions=[MisconceptionItem(**item) for item in payload.get("misconceptions", [])],
            metadata=dict(payload.get("metadata", {})),
        )


def normalize_concept_id(value: str) -> str:
    """Create a stable, ASCII-friendly concept id when the extractor does not."""
    text = str(value or "").strip().lower()
    text = re.sub(r"[\s\-/]+", "_", text)
    text = re.sub(r"[^0-9a-zA-Z_\u4e00-\u9fff]", "", text)
    text = text.strip("_")
    if not text:
        return "unknown"
    # Keep Chinese ids readable; callers may later map to pinyin if desired.
    return text[:80]


def _dedupe_by_key(items: Iterable[Any], key_fn) -> list[Any]:
    seen: set[Any] = set()
    result: list[Any] = []
    for item in items:
        key = key_fn(item)
        if key in seen:
            continue
        seen.add(key)
        result.append(item)
    return result


def merge_course_graphs(
    course_name: str, graphs: Iterable[CourseGraph], metadata: dict[str, Any] | None = None
) -> CourseGraph:
    nodes: list[CourseGraphNode] = []
    edges: list[CourseGraphEdge] = []
    tags: list[ChunkConceptTag] = []
    misconceptions: list[MisconceptionItem] = []

    for graph in graphs:
        nodes.extend(graph.nodes)
        edges.extend(graph.edges)
        tags.extend(graph.chunk_tags)
        misconceptions.extend(graph.misconceptions)

    return CourseGraph(
        course_name=course_name,
        nodes=_dedupe_by_key(nodes, lambda item: item.id),
        edges=_dedupe_by_key(edges, lambda item: (item.source, item.target, item.type)),
        chunk_tags=_dedupe_by_key(
            tags, lambda item: (item.chunk_id, tuple(sorted(item.concept_ids)), item.pedagogical_type)
        ),
        misconceptions=_dedupe_by_key(misconceptions, lambda item: item.id),
        metadata=metadata or {},
    )
